name: 'Setup netrc'
author: 'Ross MacArthur'
description: 'Append an entry to the netrc file'
branding:
  icon: 'lock'
  color: 'black'
inputs:
  machine:
    description: 'The remote machine name'
    required: true
  username:
    description: 'The remote username'
    default: ''
  password:
    description: 'The remote password'
    default: ''
runs:
  using: 'node16'
  main: 'dist/create/index.js'
  post: 'dist/remove/index.js'
  post-if: 'always()'
